// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options,
  appControllerGetHello,
  workflowControllerRun,
  workflowControllerStreamUpdates,
} from "../sdk.gen";
import {
  queryOptions,
  type UseMutationOptions,
  type DefaultError,
} from "@tanstack/react-query";
import type {
  AppControllerGetHelloData,
  WorkflowControllerRunData,
  WorkflowControllerRunResponse,
  WorkflowControllerStreamUpdatesData,
} from "../types.gen";
import { client as _heyApiClient } from "../client.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
  }
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? _heyApiClient).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const appControllerGetHelloQueryKey = (
  options?: Options<AppControllerGetHelloData>
) => createQueryKey("appControllerGetHello", options);

export const appControllerGetHelloOptions = (
  options?: Options<AppControllerGetHelloData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await appControllerGetHello({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: appControllerGetHelloQueryKey(options),
  });
};

export const workflowControllerRunQueryKey = (
  options?: Options<WorkflowControllerRunData>
) => createQueryKey("workflowControllerRun", options);

export const workflowControllerRunOptions = (
  options?: Options<WorkflowControllerRunData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await workflowControllerRun({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: workflowControllerRunQueryKey(options),
  });
};

export const workflowControllerRunMutation = (
  options?: Partial<Options<WorkflowControllerRunData>>
): UseMutationOptions<
  WorkflowControllerRunResponse,
  DefaultError,
  Options<WorkflowControllerRunData>
> => {
  const mutationOptions: UseMutationOptions<
    WorkflowControllerRunResponse,
    DefaultError,
    Options<WorkflowControllerRunData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await workflowControllerRun({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const workflowControllerStreamUpdatesQueryKey = (
  options: Options<WorkflowControllerStreamUpdatesData>
) => createQueryKey("workflowControllerStreamUpdates", options);

export const workflowControllerStreamUpdatesOptions = (
  options: Options<WorkflowControllerStreamUpdatesData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await workflowControllerStreamUpdates({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: workflowControllerStreamUpdatesQueryKey(options),
  });
};
