// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { WorkflowControllerRunData, WorkflowControllerRunResponses, WorkflowControllerStreamUpdatesData, WorkflowControllerStreamUpdatesResponses, WorkflowControllerFindAllData, WorkflowControllerFindAllResponses, WorkflowControllerCreateData, WorkflowControllerCreateResponses, WorkflowControllerFindOneData, WorkflowControllerFindOneResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const workflowControllerRun = <ThrowOnError extends boolean = false>(options: Options<WorkflowControllerRunData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<WorkflowControllerRunResponses, unknown, ThrowOnError>({
        url: '/workflow/run',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const workflowControllerStreamUpdates = <ThrowOnError extends boolean = false>(options: Options<WorkflowControllerStreamUpdatesData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<WorkflowControllerStreamUpdatesResponses, unknown, ThrowOnError>({
        url: '/workflow/stream/{runId}',
        ...options
    });
};

export const workflowControllerFindAll = <ThrowOnError extends boolean = false>(options?: Options<WorkflowControllerFindAllData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<WorkflowControllerFindAllResponses, unknown, ThrowOnError>({
        url: '/workflow',
        ...options
    });
};

export const workflowControllerCreate = <ThrowOnError extends boolean = false>(options: Options<WorkflowControllerCreateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<WorkflowControllerCreateResponses, unknown, ThrowOnError>({
        url: '/workflow',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const workflowControllerFindOne = <ThrowOnError extends boolean = false>(options: Options<WorkflowControllerFindOneData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<WorkflowControllerFindOneResponses, unknown, ThrowOnError>({
        url: '/workflow/{id}',
        ...options
    });
};