// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { AppControllerGetHelloData, AppControllerGetHelloResponses, RunnerControllerRunData, RunnerControllerRunResponses, RunnerControllerStreamUpdatesData, RunnerControllerStreamUpdatesResponses, RunnerControllerCancelData, RunnerControllerCancelResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const appControllerGetHello = <ThrowOnError extends boolean = false>(options?: Options<AppControllerGetHelloData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<AppControllerGetHelloResponses, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};

export const runnerControllerRun = <ThrowOnError extends boolean = false>(options?: Options<RunnerControllerRunData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<RunnerControllerRunResponses, unknown, ThrowOnError>({
        url: '/runner/run',
        ...options
    });
};

export const runnerControllerStreamUpdates = <ThrowOnError extends boolean = false>(options: Options<RunnerControllerStreamUpdatesData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<RunnerControllerStreamUpdatesResponses, unknown, ThrowOnError>({
        url: '/runner/stream/{jobId}',
        ...options
    });
};

export const runnerControllerCancel = <ThrowOnError extends boolean = false>(options?: Options<RunnerControllerCancelData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<RunnerControllerCancelResponses, unknown, ThrowOnError>({
        url: '/runner/cancel',
        ...options
    });
};