// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { AppControllerGetHelloData, AppControllerGetHelloResponses, WorkflowControllerRunData, WorkflowControllerRunResponses, WorkflowControllerStreamUpdatesData, WorkflowControllerStreamUpdatesResponses, WorkflowControllerFindAllData, WorkflowControllerFindAllResponses, WorkflowControllerCreateData, WorkflowControllerCreateResponses, WorkflowControllerDeleteOneData, WorkflowControllerDeleteOneResponses, WorkflowControllerFindOneData, WorkflowControllerFindOneResponses, WorkflowControllerUpdateData, WorkflowControllerUpdateResponses, WorkflowControllerFindHistoryData, WorkflowControllerFindHistoryResponses, WorkflowControllerGetLogForHistoryData, WorkflowControllerGetLogForHistoryResponses, WorkflowControllerDownloadHistoryData, WorkflowControllerDownloadHistoryResponses, DemoControllerGetDemoData, DemoControllerGetDemoResponses, DemoControllerRunDemoWorkflowData, DemoControllerRunDemoWorkflowResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const appControllerGetHello = <ThrowOnError extends boolean = false>(options?: Options<AppControllerGetHelloData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<AppControllerGetHelloResponses, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};

export const workflowControllerRun = <ThrowOnError extends boolean = false>(options: Options<WorkflowControllerRunData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<WorkflowControllerRunResponses, unknown, ThrowOnError>({
        url: '/workflow/run/{workflowId}',
        ...options
    });
};

export const workflowControllerStreamUpdates = <ThrowOnError extends boolean = false>(options: Options<WorkflowControllerStreamUpdatesData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<WorkflowControllerStreamUpdatesResponses, unknown, ThrowOnError>({
        url: '/workflow/stream/{runId}',
        ...options
    });
};

export const workflowControllerFindAll = <ThrowOnError extends boolean = false>(options?: Options<WorkflowControllerFindAllData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<WorkflowControllerFindAllResponses, unknown, ThrowOnError>({
        url: '/workflow',
        ...options
    });
};

export const workflowControllerCreate = <ThrowOnError extends boolean = false>(options: Options<WorkflowControllerCreateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<WorkflowControllerCreateResponses, unknown, ThrowOnError>({
        url: '/workflow',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const workflowControllerDeleteOne = <ThrowOnError extends boolean = false>(options: Options<WorkflowControllerDeleteOneData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<WorkflowControllerDeleteOneResponses, unknown, ThrowOnError>({
        url: '/workflow/{id}',
        ...options
    });
};

export const workflowControllerFindOne = <ThrowOnError extends boolean = false>(options: Options<WorkflowControllerFindOneData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<WorkflowControllerFindOneResponses, unknown, ThrowOnError>({
        url: '/workflow/{id}',
        ...options
    });
};

export const workflowControllerUpdate = <ThrowOnError extends boolean = false>(options: Options<WorkflowControllerUpdateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<WorkflowControllerUpdateResponses, unknown, ThrowOnError>({
        url: '/workflow/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const workflowControllerFindHistory = <ThrowOnError extends boolean = false>(options: Options<WorkflowControllerFindHistoryData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<WorkflowControllerFindHistoryResponses, unknown, ThrowOnError>({
        url: '/workflow/{id}/history',
        ...options
    });
};

export const workflowControllerGetLogForHistory = <ThrowOnError extends boolean = false>(options: Options<WorkflowControllerGetLogForHistoryData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<WorkflowControllerGetLogForHistoryResponses, unknown, ThrowOnError>({
        url: '/workflow/{id}/history/{runId}',
        ...options
    });
};

export const workflowControllerDownloadHistory = <ThrowOnError extends boolean = false>(options: Options<WorkflowControllerDownloadHistoryData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<WorkflowControllerDownloadHistoryResponses, unknown, ThrowOnError>({
        url: '/workflow/{runId}/download',
        ...options
    });
};

export const demoControllerGetDemo = <ThrowOnError extends boolean = false>(options?: Options<DemoControllerGetDemoData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<DemoControllerGetDemoResponses, unknown, ThrowOnError>({
        url: '/demo',
        ...options
    });
};

export const demoControllerRunDemoWorkflow = <ThrowOnError extends boolean = false>(options?: Options<DemoControllerRunDemoWorkflowData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<DemoControllerRunDemoWorkflowResponses, unknown, ThrowOnError>({
        url: '/demo/run',
        ...options
    });
};