// This file is auto-generated by @hey-api/openapi-ts

export type PipelineConnectionDto = {
    id: string;
    sourceNodeId: string;
    targetNodeId: string;
    sourceNodeHandleId?: string;
    targetNodeHandleId?: string;
};

export type WorkflowDto = {
    nodes: Array<LlmNodeDto | TextInputNodeDto | TextOutputNodeDto | BasicStartNodeDto | TextGenerationNodeDto | MergeNodeDto | StructuredOutputNodeDto>;
    connections: Array<PipelineConnectionDto>;
    id: string;
    name: string;
    createdAt: string;
    updatedAt: string;
};

export type WorkflowHistoryDto = {
    id: string;
    createdAt: string;
    updatedAt: string;
    status: string;
    errorMessage: string | null;
    startedAt: string;
    completedAt: string | null;
    workflowId: string;
};

export type ProgressMessageDto = {
    payload?: {
        nodeId: string;
        data?: {
            [key: string]: unknown;
        };
    };
    log: string;
};

export type ProgressMessageWithTypeDto = {
    type: 'log' | 'progress_node' | 'success_node' | 'result_success' | 'result_fail' | 'fail_node';
    payload: ProgressMessageDto;
};

export type CreateWorkflowDto = {
    nodes?: Array<LlmNodeDto | TextInputNodeDto | TextOutputNodeDto | BasicStartNodeDto | TextGenerationNodeDto | StructuredOutputNodeDto>;
    name: string;
    connections?: Array<PipelineConnectionDto>;
};

export type UpdateWorkflowDto = {
    nodes?: Array<LlmNodeDto | TextInputNodeDto | TextOutputNodeDto | BasicStartNodeDto | TextGenerationNodeDto | MergeNodeDto | StructuredOutputNodeDto>;
    connections?: Array<PipelineConnectionDto>;
    name?: string;
};

export type Position = {
    x: number;
    y: number;
};

export type LlmNodeDataDto = {
    llmProvider: 'openai' | 'google_genai' | 'openrouter';
    llmModel: 'gemini-2.5-flash' | 'gemini-2.5-flash-lite' | 'gemini-2.0-flash' | 'gemini-2.0-flash-lite' | 'gpt-5-nano' | 'gpt-4.1-mini' | 'gpt-4.1-nano' | 'gpt-4o-mini' | 'openrouter/horizon-beta' | 'openrouter/sonoma-dusk-alpha' | 'openrouter/sonoma-sky-alpha' | 'openai/gpt-oss-120b:free' | 'openai/gpt-oss-20b:free' | 'z-ai/glm-4.5-air:free' | 'moonshotai/kimi-k2:free';
};

export type LlmNodeDto = {
    id: string;
    type: 'text_input' | 'text_output' | 'text_generation' | 'basic_start' | 'llm' | 'merge' | 'structured_output';
    position: Position;
    data: LlmNodeDataDto;
};

export type BasicStartNodeDataDto = {
    [key: string]: unknown;
};

export type BasicStartNodeDto = {
    id: string;
    type: 'text_input' | 'text_output' | 'text_generation' | 'basic_start' | 'llm' | 'merge' | 'structured_output';
    position: Position;
    data: BasicStartNodeDataDto;
};

export type TextInputNodeDataDto = {
    role: {
        [key: string]: unknown;
    };
    prompt: string;
};

export type TextInputNodeDto = {
    id: string;
    type: 'text_input' | 'text_output' | 'text_generation' | 'basic_start' | 'llm' | 'merge' | 'structured_output';
    position: Position;
    data: TextInputNodeDataDto;
};

export type TextOutputNodeDataDto = {
    response: Array<{
        [key: string]: unknown;
    }>;
};

export type TextOutputNodeDto = {
    id: string;
    type: 'text_input' | 'text_output' | 'text_generation' | 'basic_start' | 'llm' | 'merge' | 'structured_output';
    position: Position;
    data: TextOutputNodeDataDto;
};

export type TextGenerationNodeDataDto = {
    [key: string]: unknown;
};

export type TextGenerationNodeDto = {
    id: string;
    type: 'text_input' | 'text_output' | 'text_generation' | 'basic_start' | 'llm' | 'merge' | 'structured_output';
    position: Position;
    data: TextGenerationNodeDataDto;
};

export type StructuredOutputNodeDataDto = {
    jsonSchema: string;
};

export type StructuredOutputNodeDto = {
    id: string;
    type: 'text_input' | 'text_output' | 'text_generation' | 'basic_start' | 'llm' | 'merge' | 'structured_output';
    position: Position;
    data: StructuredOutputNodeDataDto;
};

export type MergeInput = {
    id: string;
};

export type MergeNodeDataDto = {
    inputs: Array<MergeInput>;
};

export type MergeNodeDto = {
    id: string;
    type: 'text_input' | 'text_output' | 'text_generation' | 'basic_start' | 'llm' | 'merge' | 'structured_output';
    position: Position;
    data: MergeNodeDataDto;
};

export type AppControllerGetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppControllerGetHelloResponses = {
    200: string;
};

export type AppControllerGetHelloResponse = AppControllerGetHelloResponses[keyof AppControllerGetHelloResponses];

export type WorkflowControllerRunData = {
    body?: never;
    path: {
        workflowId: string;
    };
    query?: never;
    url: '/workflow/run/{workflowId}';
};

export type WorkflowControllerRunResponses = {
    201: string;
};

export type WorkflowControllerRunResponse = WorkflowControllerRunResponses[keyof WorkflowControllerRunResponses];

export type WorkflowControllerStreamUpdatesData = {
    body?: never;
    path: {
        runId: string;
    };
    query?: never;
    url: '/workflow/stream/{runId}';
};

export type WorkflowControllerStreamUpdatesResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type WorkflowControllerStreamUpdatesResponse = WorkflowControllerStreamUpdatesResponses[keyof WorkflowControllerStreamUpdatesResponses];

export type WorkflowControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/workflow';
};

export type WorkflowControllerFindAllResponses = {
    200: Array<WorkflowDto>;
};

export type WorkflowControllerFindAllResponse = WorkflowControllerFindAllResponses[keyof WorkflowControllerFindAllResponses];

export type WorkflowControllerCreateData = {
    body: CreateWorkflowDto;
    path?: never;
    query?: never;
    url: '/workflow';
};

export type WorkflowControllerCreateResponses = {
    201: WorkflowDto;
};

export type WorkflowControllerCreateResponse = WorkflowControllerCreateResponses[keyof WorkflowControllerCreateResponses];

export type WorkflowControllerDeleteOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/workflow/{id}';
};

export type WorkflowControllerDeleteOneResponses = {
    200: unknown;
};

export type WorkflowControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/workflow/{id}';
};

export type WorkflowControllerFindOneResponses = {
    200: WorkflowDto;
};

export type WorkflowControllerFindOneResponse = WorkflowControllerFindOneResponses[keyof WorkflowControllerFindOneResponses];

export type WorkflowControllerUpdateData = {
    body: UpdateWorkflowDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/workflow/{id}';
};

export type WorkflowControllerUpdateResponses = {
    200: WorkflowDto;
};

export type WorkflowControllerUpdateResponse = WorkflowControllerUpdateResponses[keyof WorkflowControllerUpdateResponses];

export type WorkflowControllerFindHistoryData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/workflow/{id}/history';
};

export type WorkflowControllerFindHistoryResponses = {
    200: Array<WorkflowHistoryDto>;
};

export type WorkflowControllerFindHistoryResponse = WorkflowControllerFindHistoryResponses[keyof WorkflowControllerFindHistoryResponses];

export type WorkflowControllerGetLogForHistoryData = {
    body?: never;
    path: {
        id: string;
        runId: string;
    };
    query?: never;
    url: '/workflow/{id}/history/{runId}';
};

export type WorkflowControllerGetLogForHistoryResponses = {
    200: Array<ProgressMessageWithTypeDto>;
};

export type WorkflowControllerGetLogForHistoryResponse = WorkflowControllerGetLogForHistoryResponses[keyof WorkflowControllerGetLogForHistoryResponses];

export type WorkflowControllerDownloadHistoryData = {
    body?: never;
    path: {
        runId: string;
    };
    query?: never;
    url: '/workflow/{runId}/download';
};

export type WorkflowControllerDownloadHistoryResponses = {
    200: string;
};

export type WorkflowControllerDownloadHistoryResponse = WorkflowControllerDownloadHistoryResponses[keyof WorkflowControllerDownloadHistoryResponses];

export type ClientOptions = {
    baseUrl: string;
};