// This file is auto-generated by @hey-api/openapi-ts

export type AppControllerGetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppControllerGetHelloResponses = {
    200: string;
};

export type AppControllerGetHelloResponse = AppControllerGetHelloResponses[keyof AppControllerGetHelloResponses];

export type RunnerControllerRunData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/runner/run';
};

export type RunnerControllerRunResponses = {
    201: unknown;
};

export type RunnerControllerStreamUpdatesData = {
    body?: never;
    path: {
        jobId: string;
    };
    query?: never;
    url: '/runner/stream/{jobId}';
};

export type RunnerControllerStreamUpdatesResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type RunnerControllerStreamUpdatesResponse = RunnerControllerStreamUpdatesResponses[keyof RunnerControllerStreamUpdatesResponses];

export type RunnerControllerCancelData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/runner/cancel';
};

export type RunnerControllerCancelResponses = {
    201: unknown;
};

export type ClientOptions = {
    baseUrl: string;
};