// This file is auto-generated by @hey-api/openapi-ts

export type PipelineConnectionDto = {
    id: string;
    sourceNodeId: string;
    targetNodeId: string;
    sourceNodeHandleId: string;
    targetNodeHandleId: string;
};

export type RunWorkloadDto = {
    nodes: Array<LlmNodeDto | TextInputNodeDto | TextOutputNodeDto | BasicStartNodeDto | TextGenerationNodeDto>;
    connections: Array<PipelineConnectionDto>;
};

export type WorkflowDto = {
    id: string;
    name: string;
    createdAt: string;
    updatedAt: string;
};

export type CreateWorkflowDto = {
    name: string;
};

export type LlmNodeDataDto = {
    llmProvider: 'openai' | 'google_genai';
};

export type NodeHandleDto = {
    id: string;
    type: {
        [key: string]: unknown;
    };
    handleKey: string;
};

export type LlmNodeDto = {
    id: string;
    type: 'text_input' | 'text_output' | 'text_generation' | 'basic_start' | 'llm';
    data: LlmNodeDataDto;
    handles: Array<NodeHandleDto>;
};

export type BasicStartNodeDataDto = {
    [key: string]: unknown;
};

export type BasicStartNodeDto = {
    id: string;
    type: 'text_input' | 'text_output' | 'text_generation' | 'basic_start' | 'llm';
    data: BasicStartNodeDataDto;
    handles: Array<NodeHandleDto>;
};

export type TextInputNodeDataDto = {
    prompt: string;
};

export type TextInputNodeDto = {
    id: string;
    type: 'text_input' | 'text_output' | 'text_generation' | 'basic_start' | 'llm';
    data: TextInputNodeDataDto;
    handles: Array<NodeHandleDto>;
};

export type TextOutputNodeDataDto = {
    [key: string]: unknown;
};

export type TextOutputNodeDto = {
    id: string;
    type: 'text_input' | 'text_output' | 'text_generation' | 'basic_start' | 'llm';
    data: TextOutputNodeDataDto;
    handles: Array<NodeHandleDto>;
};

export type TextGenerationNodeDataDto = {
    json_mode: boolean;
};

export type TextGenerationNodeDto = {
    id: string;
    type: 'text_input' | 'text_output' | 'text_generation' | 'basic_start' | 'llm';
    data: TextGenerationNodeDataDto;
    handles: Array<NodeHandleDto>;
};

export type WorkflowControllerRunData = {
    body: RunWorkloadDto;
    path?: never;
    query?: never;
    url: '/workflow/run';
};

export type WorkflowControllerRunResponses = {
    201: string;
};

export type WorkflowControllerRunResponse = WorkflowControllerRunResponses[keyof WorkflowControllerRunResponses];

export type WorkflowControllerStreamUpdatesData = {
    body?: never;
    path: {
        runId: string;
    };
    query?: never;
    url: '/workflow/stream/{runId}';
};

export type WorkflowControllerStreamUpdatesResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type WorkflowControllerStreamUpdatesResponse = WorkflowControllerStreamUpdatesResponses[keyof WorkflowControllerStreamUpdatesResponses];

export type WorkflowControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/workflow';
};

export type WorkflowControllerFindAllResponses = {
    200: Array<WorkflowDto>;
};

export type WorkflowControllerFindAllResponse = WorkflowControllerFindAllResponses[keyof WorkflowControllerFindAllResponses];

export type WorkflowControllerCreateData = {
    body: CreateWorkflowDto;
    path?: never;
    query?: never;
    url: '/workflow';
};

export type WorkflowControllerCreateResponses = {
    201: WorkflowDto;
};

export type WorkflowControllerCreateResponse = WorkflowControllerCreateResponses[keyof WorkflowControllerCreateResponses];

export type WorkflowControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/workflow/{id}';
};

export type WorkflowControllerFindOneResponses = {
    200: WorkflowDto;
};

export type WorkflowControllerFindOneResponse = WorkflowControllerFindOneResponses[keyof WorkflowControllerFindOneResponses];

export type ClientOptions = {
    baseUrl: string;
};