// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zPipelineConnectionDto = z.object({
    id: z.string(),
    sourceNodeId: z.string(),
    targetNodeId: z.string(),
    sourceNodeHandleId: z.string().optional(),
    targetNodeHandleId: z.string().optional()
});

export const zPosition = z.object({
    x: z.number(),
    y: z.number()
});

export const zLlmNodeDataDto = z.object({
    llmProvider: z.enum([
        'openai',
        'google_genai',
        'openrouter'
    ]),
    llmModel: z.enum([
        'gemini-2.5-flash',
        'gemini-2.5-flash-lite',
        'gemini-2.0-flash',
        'gemini-2.0-flash-lite',
        'gpt-5-nano',
        'gpt-4.1-mini',
        'gpt-4.1-nano',
        'gpt-4o-mini',
        'openrouter/horizon-beta',
        'openrouter/sonoma-dusk-alpha',
        'openrouter/sonoma-sky-alpha',
        'openai/gpt-oss-120b:free',
        'openai/gpt-oss-20b:free',
        'z-ai/glm-4.5-air:free',
        'moonshotai/kimi-k2:free'
    ])
});

export const zLlmNodeDto = z.object({
    id: z.string(),
    type: z.enum([
        'text_input',
        'text_output',
        'text_generation',
        'basic_start',
        'llm',
        'merge',
        'structured_output'
    ]),
    position: zPosition,
    data: zLlmNodeDataDto
});

export const zTextInputNodeDataDto = z.object({
    role: z.object({}),
    prompt: z.string()
});

export const zTextInputNodeDto = z.object({
    id: z.string(),
    type: z.enum([
        'text_input',
        'text_output',
        'text_generation',
        'basic_start',
        'llm',
        'merge',
        'structured_output'
    ]),
    position: zPosition,
    data: zTextInputNodeDataDto
});

export const zTextOutputNodeDataDto = z.object({
    response: z.array(z.object({})).default([])
});

export const zTextOutputNodeDto = z.object({
    id: z.string(),
    type: z.enum([
        'text_input',
        'text_output',
        'text_generation',
        'basic_start',
        'llm',
        'merge',
        'structured_output'
    ]),
    position: zPosition,
    data: zTextOutputNodeDataDto
});

export const zBasicStartNodeDataDto = z.object({});

export const zBasicStartNodeDto = z.object({
    id: z.string(),
    type: z.enum([
        'text_input',
        'text_output',
        'text_generation',
        'basic_start',
        'llm',
        'merge',
        'structured_output'
    ]),
    position: zPosition,
    data: zBasicStartNodeDataDto
});

export const zTextGenerationNodeDataDto = z.object({});

export const zTextGenerationNodeDto = z.object({
    id: z.string(),
    type: z.enum([
        'text_input',
        'text_output',
        'text_generation',
        'basic_start',
        'llm',
        'merge',
        'structured_output'
    ]),
    position: zPosition,
    data: zTextGenerationNodeDataDto
});

export const zMergeInput = z.object({
    id: z.string()
});

export const zMergeNodeDataDto = z.object({
    inputs: z.array(zMergeInput)
});

export const zMergeNodeDto = z.object({
    id: z.string(),
    type: z.enum([
        'text_input',
        'text_output',
        'text_generation',
        'basic_start',
        'llm',
        'merge',
        'structured_output'
    ]),
    position: zPosition,
    data: zMergeNodeDataDto
});

export const zStructuredOutputNodeDataDto = z.object({
    jsonSchema: z.string()
});

export const zStructuredOutputNodeDto = z.object({
    id: z.string(),
    type: z.enum([
        'text_input',
        'text_output',
        'text_generation',
        'basic_start',
        'llm',
        'merge',
        'structured_output'
    ]),
    position: zPosition,
    data: zStructuredOutputNodeDataDto
});

export const zWorkflowDto = z.object({
    nodes: z.array(z.union([
        zLlmNodeDto,
        zTextInputNodeDto,
        zTextOutputNodeDto,
        zBasicStartNodeDto,
        zTextGenerationNodeDto,
        zMergeNodeDto,
        zStructuredOutputNodeDto
    ])),
    connections: z.array(zPipelineConnectionDto),
    id: z.string(),
    name: z.string(),
    createdAt: z.string().datetime(),
    updatedAt: z.string().datetime()
});

export const zWorkflowHistoryDto = z.object({
    id: z.string(),
    createdAt: z.string().datetime(),
    updatedAt: z.string().datetime(),
    status: z.string(),
    errorMessage: z.union([
        z.string(),
        z.null()
    ]),
    startedAt: z.string().datetime(),
    completedAt: z.union([
        z.string().datetime(),
        z.null()
    ]),
    workflowId: z.string()
});

export const zProgressMessageDto = z.object({
    payload: z.object({
        nodeId: z.string(),
        data: z.object({}).optional()
    }).optional(),
    log: z.string()
});

export const zProgressMessageWithTypeDto = z.object({
    type: z.enum([
        'log',
        'progress_node',
        'success_node',
        'result_success',
        'result_fail',
        'fail_node'
    ]),
    payload: zProgressMessageDto
});

export const zCreateWorkflowDto = z.object({
    nodes: z.array(z.union([
        zLlmNodeDto,
        zTextInputNodeDto,
        zTextOutputNodeDto,
        zBasicStartNodeDto,
        zTextGenerationNodeDto,
        zStructuredOutputNodeDto
    ])).optional(),
    name: z.string(),
    connections: z.array(zPipelineConnectionDto).optional()
});

export const zUpdateWorkflowDto = z.object({
    nodes: z.array(z.union([
        zLlmNodeDto,
        zTextInputNodeDto,
        zTextOutputNodeDto,
        zBasicStartNodeDto,
        zTextGenerationNodeDto,
        zMergeNodeDto,
        zStructuredOutputNodeDto
    ])).optional(),
    connections: z.array(zPipelineConnectionDto).optional(),
    name: z.string().optional()
});

export const zAppControllerGetHelloData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zAppControllerGetHelloResponse = z.string();

export const zWorkflowControllerRunData = z.object({
    body: z.never().optional(),
    path: z.object({
        workflowId: z.string()
    }),
    query: z.never().optional()
});

export const zWorkflowControllerRunResponse = z.string();

export const zWorkflowControllerStreamUpdatesData = z.object({
    body: z.never().optional(),
    path: z.object({
        runId: z.string()
    }),
    query: z.never().optional()
});

export const zWorkflowControllerStreamUpdatesResponse = z.object({});

export const zWorkflowControllerFindAllData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zWorkflowControllerFindAllResponse = z.array(zWorkflowDto);

export const zWorkflowControllerCreateData = z.object({
    body: zCreateWorkflowDto,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zWorkflowControllerCreateResponse = zWorkflowDto;

export const zWorkflowControllerDeleteOneData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zWorkflowControllerFindOneData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zWorkflowControllerFindOneResponse = zWorkflowDto;

export const zWorkflowControllerUpdateData = z.object({
    body: zUpdateWorkflowDto,
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zWorkflowControllerUpdateResponse = zWorkflowDto;

export const zWorkflowControllerFindHistoryData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zWorkflowControllerFindHistoryResponse = z.array(zWorkflowHistoryDto);

export const zWorkflowControllerGetLogForHistoryData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string(),
        runId: z.string()
    }),
    query: z.never().optional()
});

export const zWorkflowControllerGetLogForHistoryResponse = z.array(zProgressMessageWithTypeDto);

export const zWorkflowControllerDownloadHistoryData = z.object({
    body: z.never().optional(),
    path: z.object({
        runId: z.string()
    }),
    query: z.never().optional()
});

export const zWorkflowControllerDownloadHistoryResponse = z.string();