// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zPipelineConnectionDto = z.object({
    id: z.string(),
    sourceNodeId: z.string(),
    targetNodeId: z.string(),
    sourceNodeHandleId: z.string(),
    targetNodeHandleId: z.string()
});

export const zLlmNodeDataDto = z.object({
    llmProvider: z.enum([
        'openai',
        'google_genai',
        'openrouter'
    ]),
    llmModel: z.enum([
        'gemini-2.5-flash',
        'gemini-2.5-flash-lite',
        'gemini-2.0-flash',
        'gemini-2.0-flash-lite',
        'gpt-5-nano',
        'gpt-4.1-mini',
        'gpt-4.1-nano',
        'gpt-4o-mini'
    ])
});

export const zPosition = z.object({
    x: z.number(),
    y: z.number()
});

export const zLlmNodeDto = z.object({
    id: z.string(),
    type: z.enum([
        'text_input',
        'text_output',
        'text_generation',
        'basic_start',
        'llm',
        'merge',
        'structured_output'
    ]),
    data: zLlmNodeDataDto,
    position: zPosition
});

export const zTextInputNodeDataDto = z.object({
    role: z.object({}),
    prompt: z.string()
});

export const zTextInputNodeDto = z.object({
    id: z.string(),
    type: z.enum([
        'text_input',
        'text_output',
        'text_generation',
        'basic_start',
        'llm',
        'merge',
        'structured_output'
    ]),
    data: zTextInputNodeDataDto,
    position: zPosition
});

export const zTextOutputNodeDataDto = z.object({
    response: z.array(z.object({})).default([])
});

export const zTextOutputNodeDto = z.object({
    id: z.string(),
    type: z.enum([
        'text_input',
        'text_output',
        'text_generation',
        'basic_start',
        'llm',
        'merge',
        'structured_output'
    ]),
    data: zTextOutputNodeDataDto,
    position: zPosition
});

export const zBasicStartNodeDataDto = z.object({});

export const zBasicStartNodeDto = z.object({
    id: z.string(),
    type: z.enum([
        'text_input',
        'text_output',
        'text_generation',
        'basic_start',
        'llm',
        'merge',
        'structured_output'
    ]),
    data: zBasicStartNodeDataDto,
    position: zPosition
});

export const zTextGenerationNodeDataDto = z.object({});

export const zTextGenerationNodeDto = z.object({
    id: z.string(),
    type: z.enum([
        'text_input',
        'text_output',
        'text_generation',
        'basic_start',
        'llm',
        'merge',
        'structured_output'
    ]),
    data: zTextGenerationNodeDataDto,
    position: zPosition
});

export const zMergeNodeDataDto = z.object({
    inputs: z.array(z.object({
        id: z.string()
    }))
});

export const zMergeNodeDto = z.object({
    id: z.string(),
    type: z.enum([
        'text_input',
        'text_output',
        'text_generation',
        'basic_start',
        'llm',
        'merge',
        'structured_output'
    ]),
    data: zMergeNodeDataDto,
    position: zPosition
});

export const zStructuredOutputNodeDataDto = z.object({
    jsonSchema: z.string()
});

export const zStructuredOutputNodeDto = z.object({
    id: z.string(),
    type: z.enum([
        'text_input',
        'text_output',
        'text_generation',
        'basic_start',
        'llm',
        'merge',
        'structured_output'
    ]),
    data: zStructuredOutputNodeDataDto,
    position: zPosition
});

export const zWorkflowDto = z.object({
    nodes: z.array(z.union([
        zLlmNodeDto,
        zTextInputNodeDto,
        zTextOutputNodeDto,
        zBasicStartNodeDto,
        zTextGenerationNodeDto,
        zMergeNodeDto,
        zStructuredOutputNodeDto
    ])),
    connections: z.array(zPipelineConnectionDto),
    id: z.string(),
    name: z.string(),
    createdAt: z.string().datetime(),
    updatedAt: z.string().datetime()
});

export const zCreateWorkflowDto = z.object({
    nodes: z.array(z.union([
        zLlmNodeDto,
        zTextInputNodeDto,
        zTextOutputNodeDto,
        zBasicStartNodeDto,
        zTextGenerationNodeDto
    ])).optional(),
    name: z.string(),
    connections: z.array(zPipelineConnectionDto).optional()
});

export const zUpdateWorkflowDto = z.object({
    nodes: z.array(z.union([
        zLlmNodeDto,
        zTextInputNodeDto,
        zTextOutputNodeDto,
        zBasicStartNodeDto,
        zTextGenerationNodeDto,
        zMergeNodeDto,
        zStructuredOutputNodeDto
    ])).optional(),
    connections: z.array(zPipelineConnectionDto).optional(),
    name: z.string().optional()
});

export const zAppControllerGetHelloData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zAppControllerGetHelloResponse = z.string();

export const zWorkflowControllerRunData = z.object({
    body: z.never().optional(),
    path: z.object({
        workflowId: z.string()
    }),
    query: z.never().optional()
});

export const zWorkflowControllerRunResponse = z.string();

export const zWorkflowControllerStreamUpdatesData = z.object({
    body: z.never().optional(),
    path: z.object({
        runId: z.string()
    }),
    query: z.never().optional()
});

export const zWorkflowControllerStreamUpdatesResponse = z.object({});

export const zWorkflowControllerFindAllData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zWorkflowControllerFindAllResponse = z.array(zWorkflowDto);

export const zWorkflowControllerCreateData = z.object({
    body: zCreateWorkflowDto,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zWorkflowControllerCreateResponse = zWorkflowDto;

export const zWorkflowControllerDeleteOneData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zWorkflowControllerFindOneData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zWorkflowControllerFindOneResponse = zWorkflowDto;

export const zWorkflowControllerUpdateData = z.object({
    body: zUpdateWorkflowDto,
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zWorkflowControllerUpdateResponse = zWorkflowDto;